Repository brstu/OTIS-2023, pull requests merged in 2023-12, with the labels that each got.

#58 [task_02] Add Solution
  readme.md
  trunk/ii02418/task_02/doc/graphic.png
  trunk/ii02418/task_02/doc/readme.md
  trunk/ii02418/task_02/src/CMakeLists.txt
  trunk/ii02418/task_02/src/OTIS_02.cpp
Labels: invalid

#68 [task_02] Add a problem solution
  readme.md
  trunk/ii02304/task_02/doc/chart.png
  trunk/ii02304/task_02/doc/report2.md
  trunk/ii02304/task_02/src/CMakeLists.txt
  trunk/ii02304/task_02/src/CMakeProjectOTIS2LABA.cpp
Labels: invalid

#84 [task_02] Add solution
  readme.md
  trunk/ii02419/task_02/doc/laba2otis.jpeg
  trunk/ii02419/task_02/doc/readme.md
  trunk/ii02419/task_02/src/CMakeLists.txt
  trunk/ii02419/task_02/src/main.cpp
Labels: question

#154 [task_03] Add solution problem
  readme.md
  trunk/ii02406/doc/img/add_adjes.png
  trunk/ii02406/doc/img/add_vertex.png
  trunk/ii02406/doc/img/change_weight.png
  trunk/ii02406/doc/img/eulerian_path.png
  trunk/ii02406/doc/readme.md
  trunk/ii02406/src/CMakeLists.txt
  trunk/ii02406/src/main.cpp
Labels: good pull request

#179 [task_03] Add Solution
  readme.md
  trunk/ii02423/task_03/doc/interface.png
  trunk/ii02423/task_03/doc/readme.md
  trunk/ii02423/task_03/src/CMakeLists.txt
  trunk/ii02423/task_03/src/color_wheel.png
  trunk/ii02423/task_03/src/main.cpp
  trunk/ii02423/task_03/src/main.pde
Labels: question

#215 [task_03] Add problem solution
  readme.md
  trunk/ii02401/lab_03/doc/image-1.png
  trunk/ii02401/lab_03/doc/image-2.png
  trunk/ii02401/lab_03/doc/image-3.png
  trunk/ii02401/lab_03/doc/image-4.png
  trunk/ii02401/lab_03/doc/image-5.png
  trunk/ii02401/lab_03/doc/image-6.png
  trunk/ii02401/lab_03/doc/image.png
  trunk/ii02401/lab_03/doc/readme.md
  trunk/ii02401/lab_03/src/CMakeLists.txt
  trunk/ii02401/lab_03/src/OTIS3.cpp
  trunk/ii02401/lab_03/src/OTIS3.py
Labels: question

#168 [task_03] Add Solution
  readme.md
  trunk/ii02418/task_03/doc/images/Shortest_Path.png
  trunk/ii02418/task_03/doc/images/add_color.png
  trunk/ii02418/task_03/doc/images/add_edge.png
  trunk/ii02418/task_03/doc/images/add_vertex.png
  trunk/ii02418/task_03/doc/images/change_color.png
  trunk/ii02418/task_03/doc/images/change_name.png
  trunk/ii02418/task_03/doc/images/change_weight.png
  trunk/ii02418/task_03/doc/images/delete.png
  trunk/ii02418/task_03/doc/images/euler_path.png
  trunk/ii02418/task_03/doc/images/move.png
  trunk/ii02418/task_03/doc/images/windows.png
  trunk/ii02418/task_03/doc/readme.md
  trunk/ii02418/task_03/src/CMakeLists.txt
  trunk/ii02418/task_03/src/task.cpp
  trunk/ii02418/task_03/src/task.py
Labels: question, good pull request

#337 [task_02] [task_03] [task_04] [task_05] [task_06] Add solution
  readme.md
Labels: title needs formatting

#254 [task_03] Add problem solution
  readme.md
  trunk/ii02320/task_03/CMakeLists.txt
  trunk/ii02320/task_03/doc/1.png
  trunk/ii02320/task_03/doc/2.png
  trunk/ii02320/task_03/doc/3.jpg
  trunk/ii02320/task_03/doc/4.png
  trunk/ii02320/task_03/doc/5.png
  trunk/ii02320/task_03/doc/6.jpg
  trunk/ii02320/task_03/doc/readme.md
  trunk/ii02320/task_03/graph_LIB.h
  trunk/ii02320/task_03/graphwindow.cpp
  trunk/ii02320/task_03/graphwindow.h
  trunk/ii02320/task_03/graphwindow.ui
  trunk/ii02320/task_03/main.cpp
  trunk/ii02320/task_03/mainwindow.cpp
  trunk/ii02320/task_03/mainwindow.h
  trunk/ii02320/task_03/mainwindow.ui
Labels: bug

#347 [task_05] Add problem solution (update readme)
  readme.md
Labels: question

#270 [task_04] Add problem solution
  readme.md
  trunk/ii02405/doc/picture1.jfif
  trunk/ii02405/doc/picture2.jfif
  trunk/ii02405/doc/picture3.jfif
  trunk/ii02405/doc/picture4.jfif
  trunk/ii02405/doc/picture5.jfif
  trunk/ii02405/doc/readme.md
Labels: question
