Repository brstu/OTIS-2023, pull requests merged in 2023-11, with the labels that each got.

#19 [task_02] Add problem solution
  readme.md
  trunk/ii02408/task_02/doc/1.png
  trunk/ii02408/task_02/doc/2.png
  trunk/ii02408/task_02/doc/3.png
  trunk/ii02408/task_02/doc/4.png
  trunk/ii02408/task_02/doc/image (1).png
  trunk/ii02408/task_02/doc/report.md
  trunk/ii02408/task_02/src/CMakeLists.txt
  trunk/ii02408/task_02/src/main.cpp
Labels: question

#26 [task_05] Add problem solution
  readme.md
  trunk/ii02320/task_05/doc/1.png
  trunk/ii02320/task_05/doc/2.png
  trunk/ii02320/task_05/doc/report.md
Labels: question

#104 Revert "[task_01] Add solution"
  readme.md
  trunk/II02422/task_01/doc/liniya.jpg
  trunk/II02422/task_01/doc/neliniya.jpg
  trunk/II02422/task_01/doc/readme.md
  trunk/II02422/task_01/src/lab1.cpp
Labels: title needs formatting

#47 [task_01] Add problem solution
  readme.md
  trunk/ii02304/task_01/doc/picture.jpg
  trunk/ii02304/task_01/doc/report.md
  trunk/ii02304/task_01/src/CMakeLists.txt
  trunk/ii02304/task_01/src/CMakeProject1lab1otis.cpp
Labels: bug

#62 [task_04] Add Solution
  readme.md
  trunk/ii02418/task_04/doc/img1.png
  trunk/ii02418/task_04/doc/img2.png
  trunk/ii02418/task_04/doc/img3.png
  trunk/ii02418/task_04/doc/img4.png
  trunk/ii02418/task_04/doc/img5.png
  trunk/ii02418/task_04/doc/img6.png
  trunk/ii02418/task_04/doc/report.md
Labels: question

#77 [task_01] Add problem solution
  readme.md
  trunk/ii02415/task_01/doc/picture.png
  trunk/ii02415/task_01/doc/readme.md
  trunk/ii02415/task_01/src/CMakeLists.txt
  trunk/ii02415/task_01/src/otis_lab1.cpp
Labels: question

#85 [task_02] Add solution
  readme.md
  trunk/II02422/task_02/doc/graph.jpg
  trunk/II02422/task_02/doc/readme.md
  trunk/II02422/task_02/src/CMakeLists.txt
  trunk/II02422/task_02/src/lab2.cpp
Labels: bug

#91 [task_05] Add problem solution
  readme.md
  trunk/ii02412/task_05/doc/picture1.png
  trunk/ii02412/task_05/doc/picture2.png
  trunk/ii02412/task_05/doc/report.md
Labels: bug

#97 [doc] Add user info
  readme.md
Labels: question
